"""empty message

Revision ID: 873d4d467f1a
Revises: 22204bcb58ac
Create Date: 2025-07-30 17:19:49.414825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873d4d467f1a'
down_revision = '22204bcb58ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
